// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_applications.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createJobApplication = `-- name: CreateJobApplication :one
INSERT INTO job_applications (
  company, position, link, status, notes
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, company, position, link, status, notes, created_at, updated_at
`

type CreateJobApplicationParams struct {
	Company  string
	Position string
	Link     string
	Status   JobStatus
	Notes    string
}

func (q *Queries) CreateJobApplication(ctx context.Context, arg CreateJobApplicationParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, createJobApplication,
		arg.Company,
		arg.Position,
		arg.Link,
		arg.Status,
		arg.Notes,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Position,
		&i.Link,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobApplication = `-- name: DeleteJobApplication :exec
DELETE FROM job_applications
WHERE id = $1
`

func (q *Queries) DeleteJobApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJobApplication, id)
	return err
}

const getJobApplication = `-- name: GetJobApplication :one
SELECT id, company, position, link, status, notes, created_at, updated_at FROM job_applications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJobApplication(ctx context.Context, id uuid.UUID) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, getJobApplication, id)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Position,
		&i.Link,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const importJobApplicationFromCSV = `-- name: ImportJobApplicationFromCSV :one
INSERT INTO job_applications (
  company, position, link, status, notes, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, company, position, link, status, notes, created_at, updated_at
`

type ImportJobApplicationFromCSVParams struct {
	Company   string
	Position  string
	Link      string
	Status    JobStatus
	Notes     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ImportJobApplicationFromCSV(ctx context.Context, arg ImportJobApplicationFromCSVParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, importJobApplicationFromCSV,
		arg.Company,
		arg.Position,
		arg.Link,
		arg.Status,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Position,
		&i.Link,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobApplications = `-- name: ListJobApplications :many
SELECT id, company, position, link, status, notes, created_at, updated_at FROM job_applications
ORDER BY created_at DESC
`

func (q *Queries) ListJobApplications(ctx context.Context) ([]JobApplication, error) {
	rows, err := q.db.QueryContext(ctx, listJobApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Position,
			&i.Link,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobApplication = `-- name: UpdateJobApplication :one
UPDATE job_applications
SET
  company = $1,
  position = $2,
  link = $3,
  status = $4,
  notes = $5,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, company, position, link, status, notes, created_at, updated_at
`

type UpdateJobApplicationParams struct {
	Company  string
	Position string
	Link     string
	Status   JobStatus
	Notes    string
	ID       uuid.UUID
}

func (q *Queries) UpdateJobApplication(ctx context.Context, arg UpdateJobApplicationParams) (JobApplication, error) {
	row := q.db.QueryRowContext(ctx, updateJobApplication,
		arg.Company,
		arg.Position,
		arg.Link,
		arg.Status,
		arg.Notes,
		arg.ID,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Position,
		&i.Link,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
