// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type JobStatus string

const (
	JobStatusApplied   JobStatus = "applied"
	JobStatusInterview JobStatus = "interview"
	JobStatusOffer     JobStatus = "offer"
	JobStatusRejected  JobStatus = "rejected"
	JobStatusWithdrawn JobStatus = "withdrawn"
	JobStatusGhosted   JobStatus = "ghosted"
	JobStatusAccepted  JobStatus = "accepted"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type JobApplication struct {
	ID        uuid.UUID
	Company   string
	Position  string
	Link      string
	Status    JobStatus
	Notes     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
