services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctrl-alt-me-api
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_PORT=8080
      - BACKEND_PORT=3000
      - FRONTEND_HOST=frontend
    volumes:
      - sqlite_data:/app/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ctrl-alt-me-frontend
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_PORT=8080
      - VITE_API_URL=http://api:3000
    depends_on:
      - api

volumes:
  sqlite_data:
