#!/bin/bash

# Starts the development database using Docker
# Make sure you have Docker installed: https://docs.docker.com/engine/install/

set -e

if ! command -v docker &> /dev/null
then
    echo "docker could not be found, please install it first."
    exit
fi

# Load environment variables from .env file
if [ -f .env ]; then
  export $(grep -v '^#' ./.env | xargs)
else
  echo ".env file not found!"
  exit 1
fi

echo "Environment variables loaded from .env"

docker compose -f docker-compose.yml up -d
