#!/bin/bash

# Starts the development database using Docker
# Make sure you have Docker installed: https://docs.docker.com/engine/install/

set -e

if ! command -v docker &> /dev/null
then
    echo "docker could not be found, please install it first."
    exit
fi

# Load environment variables from .env.dev file
if [ -f .env.dev ]; then
  export $(grep -v '^#' ./.env.dev | xargs)
else
  echo ".env.dev file not found!"
  exit 1
fi

echo "Environment variables loaded from .env.dev"

docker compose -f docker-compose.yml up -d
